site_name: PyHello
theme:
  name: material

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - PyHello: index.md
  - Abstracts Objects: assets.md
  - Programing Constructs: design-patterns.md
  - Package:
    - shapes: shapes.md
    - assets: assets.md
    - area: area.md
